import collections.abc
import numpy
import numpy.typing
import typing
from typing import overload

FIXED_EXPONENT: int

class AnisotropicMonteCarloBarostat_f32(MonteCarloBarostat_f32):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, pressure: typing.SupportsFloat | typing.SupportsIndex, temperature: typing.SupportsFloat | typing.SupportsIndex, group_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], interval: typing.SupportsInt | typing.SupportsIndex, bps, seed: typing.SupportsInt | typing.SupportsIndex, adaptive_scaling_enabled: bool, initial_volume_scale_factor: typing.SupportsFloat | typing.SupportsIndex, scale_x: bool = ..., scale_y: bool = ..., scale_z: bool = ...) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class AnisotropicMonteCarloBarostat_f64(MonteCarloBarostat_f64):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, pressure: typing.SupportsFloat | typing.SupportsIndex, temperature: typing.SupportsFloat | typing.SupportsIndex, group_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], interval: typing.SupportsInt | typing.SupportsIndex, bps, seed: typing.SupportsInt | typing.SupportsIndex, adaptive_scaling_enabled: bool, initial_volume_scale_factor: typing.SupportsFloat | typing.SupportsIndex, scale_x: bool = ..., scale_y: bool = ..., scale_z: bool = ...) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class BDExchangeMove_f32(Mover_f32):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, target_mols: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], temperature: typing.SupportsFloat | typing.SupportsIndex, cutoff: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex, num_proposals_per_move: typing.SupportsInt | typing.SupportsIndex, interval: typing.SupportsInt | typing.SupportsIndex, batch_size: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def acceptance_fraction(self) -> list[float]: ...
    def compute_incremental_log_weights(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], mol_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], quaternions: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> list[list[float]]: ...
    def compute_initial_log_weights(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> list[float]: ...
    def get_after_log_weights(self) -> list[float]: ...
    def get_before_log_weights(self) -> list[float]: ...
    def get_params(self) -> numpy.typing.NDArray[numpy.float32]: ...
    def last_log_probability(self) -> float: ...
    def last_raw_log_probability(self) -> float: ...
    def move(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> tuple: ...
    def n_accepted(self) -> list[int]: ...
    def n_proposed(self) -> list[int]: ...
    def num_systems(self) -> int: ...
    def set_params(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class BDExchangeMove_f64(Mover_f64):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, target_mols: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], temperature: typing.SupportsFloat | typing.SupportsIndex, cutoff: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex, num_proposals_per_move: typing.SupportsInt | typing.SupportsIndex, interval: typing.SupportsInt | typing.SupportsIndex, batch_size: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def acceptance_fraction(self) -> list[float]: ...
    def compute_incremental_log_weights(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], mol_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], quaternions: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> list[list[float]]: ...
    def compute_initial_log_weights(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> list[float]: ...
    def get_after_log_weights(self) -> list[float]: ...
    def get_before_log_weights(self) -> list[float]: ...
    def get_params(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def last_log_probability(self) -> float: ...
    def last_raw_log_probability(self) -> float: ...
    def move(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> tuple: ...
    def n_accepted(self) -> list[int]: ...
    def n_proposed(self) -> list[int]: ...
    def num_systems(self) -> int: ...
    def set_params(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class BoundPotential_f32:
    def __init__(self, potential: Potential_f32, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    def execute(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], compute_du_dx: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], compute_du_dx: bool, compute_u: bool) -> tuple: ...
    def execute_fixed(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> numpy.typing.NDArray[numpy.uint64]: ...
    def get_flat_params(self) -> list[float]: ...
    def get_potential(self) -> Potential_f32: ...
    def num_systems(self) -> int: ...
    def set_params(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    def size(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class BoundPotential_f64:
    def __init__(self, potential: Potential_f64, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    def execute(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], compute_du_dx: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], compute_du_dx: bool, compute_u: bool) -> tuple: ...
    def execute_fixed(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.uint64]: ...
    def get_flat_params(self) -> list[float]: ...
    def get_potential(self) -> Potential_f64: ...
    def num_systems(self) -> int: ...
    def set_params(self, params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    def size(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class CentroidRestraint_f32(Potential_f32):
    def __init__(self, group_a_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], group_b_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], kb: typing.SupportsFloat | typing.SupportsIndex, b0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class CentroidRestraint_f64(Potential_f64):
    def __init__(self, group_a_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], group_b_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], kb: typing.SupportsFloat | typing.SupportsIndex, b0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ChiralAtomRestraint_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ChiralAtomRestraint_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ChiralBondRestraint_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], signs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], signs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ChiralBondRestraint_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], signs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], signs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ConstrainedLangevinIntegrator_f32(LangevinIntegrator_f32):
    def __init__(self, masses: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], temperature: typing.SupportsFloat | typing.SupportsIndex, dt: typing.SupportsFloat | typing.SupportsIndex, friction: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex, constraints: ConstraintGroups_f32) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ConstrainedLangevinIntegrator_f64(LangevinIntegrator_f64):
    def __init__(self, masses: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], temperature: typing.SupportsFloat | typing.SupportsIndex, dt: typing.SupportsFloat | typing.SupportsIndex, friction: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex, constraints: ConstraintGroups_f64) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ConstraintGroups_f32:
    def __init__(self, masses: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], groups: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], distances: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], iterations: typing.SupportsInt | typing.SupportsIndex, tolerance: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def constrain_positions(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32] | None = ...) -> numpy.typing.NDArray[numpy.float32]: ...
    def constrain_velocities(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], velocities: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32] | None = ...) -> numpy.typing.NDArray[numpy.float32]: ...
    def iterations(self) -> int: ...
    def max_group_size(self) -> int: ...
    def n_groups(self) -> int: ...
    def num_atoms(self) -> int: ...
    def num_systems(self) -> int: ...
    def tolerance(self) -> float: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class ConstraintGroups_f64:
    def __init__(self, masses: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], groups: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], distances: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], iterations: typing.SupportsInt | typing.SupportsIndex, tolerance: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def constrain_positions(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32] | None = ...) -> numpy.typing.NDArray[numpy.float64]: ...
    def constrain_velocities(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], velocities: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32] | None = ...) -> numpy.typing.NDArray[numpy.float64]: ...
    def iterations(self) -> int: ...
    def max_group_size(self) -> int: ...
    def n_groups(self) -> int: ...
    def num_atoms(self) -> int: ...
    def num_systems(self) -> int: ...
    def tolerance(self) -> float: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Context_f32:
    def __init__(self, x0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], v0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], integrator: Integrator_f32, bps: collections.abc.Sequence[BoundPotential_f32], movers: collections.abc.Sequence[Mover_f32] | None = ...) -> None: ...
    def finalize(self) -> None: ...
    def get_barostat(self) -> MonteCarloBarostat_f32: ...
    def get_box(self) -> numpy.typing.NDArray[numpy.float32]: ...
    def get_integrator(self) -> Integrator_f32: ...
    def get_local_md_potentials(self) -> list[BoundPotential_f32]: ...
    def get_movers(self) -> list[Mover_f32]: ...
    def get_potentials(self) -> list[BoundPotential_f32]: ...
    def get_v_t(self) -> numpy.typing.NDArray[numpy.float32]: ...
    def get_x_t(self) -> numpy.typing.NDArray[numpy.float32]: ...
    def initialize(self) -> None: ...
    def multiple_steps(self, n_steps: typing.SupportsInt | typing.SupportsIndex, store_x_interval: typing.SupportsInt | typing.SupportsIndex = ...) -> tuple: ...
    def multiple_steps_local(self, n_steps: typing.SupportsInt | typing.SupportsIndex, local_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], store_x_interval: typing.SupportsInt | typing.SupportsIndex = ..., radius: typing.SupportsFloat | typing.SupportsIndex = ..., k: typing.SupportsFloat | typing.SupportsIndex = ..., seed: typing.SupportsInt | typing.SupportsIndex = ...) -> tuple: ...
    def multiple_steps_local_selection(self, n_steps: typing.SupportsInt | typing.SupportsIndex, reference_idx: typing.SupportsInt | typing.SupportsIndex, selection_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], store_x_interval: typing.SupportsInt | typing.SupportsIndex = ..., radius: typing.SupportsFloat | typing.SupportsIndex = ..., k: typing.SupportsFloat | typing.SupportsIndex = ...) -> tuple: ...
    def set_box(self, box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    def set_v_t(self, velocities: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    def set_x_t(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    def setup_local_md(self, temperature: typing.SupportsFloat | typing.SupportsIndex, freeze_reference: bool, nblist_padding: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def step(self) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Context_f64:
    def __init__(self, x0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], v0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], integrator: Integrator_f64, bps: collections.abc.Sequence[BoundPotential_f64], movers: collections.abc.Sequence[Mover_f64] | None = ...) -> None: ...
    def finalize(self) -> None: ...
    def get_barostat(self) -> MonteCarloBarostat_f64: ...
    def get_box(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def get_integrator(self) -> Integrator_f64: ...
    def get_local_md_potentials(self) -> list[BoundPotential_f64]: ...
    def get_movers(self) -> list[Mover_f64]: ...
    def get_potentials(self) -> list[BoundPotential_f64]: ...
    def get_v_t(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def get_x_t(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def initialize(self) -> None: ...
    def multiple_steps(self, n_steps: typing.SupportsInt | typing.SupportsIndex, store_x_interval: typing.SupportsInt | typing.SupportsIndex = ...) -> tuple: ...
    def multiple_steps_local(self, n_steps: typing.SupportsInt | typing.SupportsIndex, local_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], store_x_interval: typing.SupportsInt | typing.SupportsIndex = ..., radius: typing.SupportsFloat | typing.SupportsIndex = ..., k: typing.SupportsFloat | typing.SupportsIndex = ..., seed: typing.SupportsInt | typing.SupportsIndex = ...) -> tuple: ...
    def multiple_steps_local_selection(self, n_steps: typing.SupportsInt | typing.SupportsIndex, reference_idx: typing.SupportsInt | typing.SupportsIndex, selection_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], store_x_interval: typing.SupportsInt | typing.SupportsIndex = ..., radius: typing.SupportsFloat | typing.SupportsIndex = ..., k: typing.SupportsFloat | typing.SupportsIndex = ...) -> tuple: ...
    def set_box(self, box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    def set_v_t(self, velocities: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    def set_x_t(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    def setup_local_md(self, temperature: typing.SupportsFloat | typing.SupportsIndex, freeze_reference: bool, nblist_padding: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def step(self) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class FanoutSummedPotential_f32(Potential_f32):
    def __init__(self, potentials: collections.abc.Sequence[Potential_f32], parallel: bool = ...) -> None: ...
    def get_potentials(self) -> list[Potential_f32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class FanoutSummedPotential_f64(Potential_f64):
    def __init__(self, potentials: collections.abc.Sequence[Potential_f64], parallel: bool = ...) -> None: ...
    def get_potentials(self) -> list[Potential_f64]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class FlatBottomBond_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def get_num_bonds(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class FlatBottomBond_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def get_num_bonds(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class FlatBottomRestraint_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, atom_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], restraint_coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, atom_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], restraint_coords: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float32]]) -> None: ...
    def get_num_atoms(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class FlatBottomRestraint_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, atom_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], restraint_coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, atom_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], restraint_coords: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64]]) -> None: ...
    def get_num_atoms(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HarmonicAngle_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, angle_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, angle_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HarmonicAngle_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, angle_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, angle_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HarmonicBond_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HarmonicBond_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HarmonicTorsion_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HarmonicTorsion_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HilbertSort_f32:
    def __init__(self, size: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def sort(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.uint32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class HilbertSort_f64:
    def __init__(self, size: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def sort(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.uint32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Integrator_f32:
    def __init__(self, *args, **kwargs) -> None: ...
    def num_systems(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Integrator_f64:
    def __init__(self, *args, **kwargs) -> None: ...
    def num_systems(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class InvalidHardware(Exception): ...

class LangevinIntegrator_f32(Integrator_f32):
    def __init__(self, masses: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], temperature: typing.SupportsFloat | typing.SupportsIndex, dt: typing.SupportsFloat | typing.SupportsIndex, friction: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class LangevinIntegrator_f64(Integrator_f64):
    def __init__(self, masses: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], temperature: typing.SupportsFloat | typing.SupportsIndex, dt: typing.SupportsFloat | typing.SupportsIndex, friction: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class LogFlatBottomBond_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], beta: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], beta: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_num_bonds(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class LogFlatBottomBond_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], beta: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, bond_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], beta: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_num_bonds(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class MonteCarloBarostat_f32(Mover_f32):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, pressure: typing.SupportsFloat | typing.SupportsIndex, temperature: typing.SupportsFloat | typing.SupportsIndex, group_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], interval: typing.SupportsInt | typing.SupportsIndex, bps, seed: typing.SupportsInt | typing.SupportsIndex, adaptive_scaling_enabled: bool, initial_volume_scale_factor: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_adaptive_scaling(self) -> bool: ...
    def get_volume_scale_factor(self) -> list[float]: ...
    def set_adaptive_scaling(self, adaptive_scaling_enabled: bool) -> None: ...
    def set_pressure(self, pressure: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def set_volume_scale_factor(self, volume_scale_factor: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class MonteCarloBarostat_f64(Mover_f64):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, pressure: typing.SupportsFloat | typing.SupportsIndex, temperature: typing.SupportsFloat | typing.SupportsIndex, group_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], interval: typing.SupportsInt | typing.SupportsIndex, bps, seed: typing.SupportsInt | typing.SupportsIndex, adaptive_scaling_enabled: bool, initial_volume_scale_factor: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_adaptive_scaling(self) -> bool: ...
    def get_volume_scale_factor(self) -> list[float]: ...
    def set_adaptive_scaling(self, adaptive_scaling_enabled: bool) -> None: ...
    def set_pressure(self, pressure: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def set_volume_scale_factor(self, volume_scale_factor: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Mover_f32:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_interval(self) -> int: ...
    def move(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> tuple: ...
    def num_systems(self) -> int: ...
    def set_interval(self, interval: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def set_step(self, step: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Mover_f64:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_interval(self) -> int: ...
    def move(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> tuple: ...
    def num_systems(self) -> int: ...
    def set_interval(self, interval: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def set_step(self, step: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Neighborlist_f32:
    def __init__(self, num_systems: typing.SupportsInt | typing.SupportsIndex, N: typing.SupportsInt | typing.SupportsIndex, compute_upper_triangular: bool) -> None: ...
    def compute_block_bounds(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], block_size: typing.SupportsInt | typing.SupportsIndex) -> tuple: ...
    def get_max_ixn_count(self) -> int: ...
    def get_nblist(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], cutoff: typing.SupportsFloat | typing.SupportsIndex, padding: typing.SupportsFloat | typing.SupportsIndex) -> list[list[list[int]]]: ...
    def get_num_row_idxs(self) -> int: ...
    def get_num_systems(self) -> int: ...
    def get_tile_ixn_count(self) -> list[int]: ...
    def reset_row_idxs(self) -> None: ...
    def resize(self, size: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def set_row_idxs(self, idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]) -> None: ...
    @overload
    def set_row_idxs_and_col_idxs(self, row_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], col_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]) -> None: ...
    @overload
    def set_row_idxs_and_col_idxs(self, row_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]], col_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Neighborlist_f64:
    def __init__(self, num_systems: typing.SupportsInt | typing.SupportsIndex, N: typing.SupportsInt | typing.SupportsIndex, compute_upper_triangular: bool) -> None: ...
    def compute_block_bounds(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], block_size: typing.SupportsInt | typing.SupportsIndex) -> tuple: ...
    def get_max_ixn_count(self) -> int: ...
    def get_nblist(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], cutoff: typing.SupportsFloat | typing.SupportsIndex, padding: typing.SupportsFloat | typing.SupportsIndex) -> list[list[list[int]]]: ...
    def get_num_row_idxs(self) -> int: ...
    def get_num_systems(self) -> int: ...
    def get_tile_ixn_count(self) -> list[int]: ...
    def reset_row_idxs(self) -> None: ...
    def resize(self, size: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def set_row_idxs(self, idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]) -> None: ...
    @overload
    def set_row_idxs_and_col_idxs(self, row_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], col_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]) -> None: ...
    @overload
    def set_row_idxs_and_col_idxs(self, row_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]], col_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.uint32]]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedExclusions_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], scales_i: numpy.typing.NDArray[numpy.float32], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: list[numpy.typing.NDArray[numpy.int32]], scales_i: list[numpy.typing.NDArray[numpy.float32]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def get_scales(self) -> numpy.typing.NDArray[numpy.float32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedExclusions_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], scales_i: numpy.typing.NDArray[numpy.float64], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: list[numpy.typing.NDArray[numpy.int32]], scales_i: list[numpy.typing.NDArray[numpy.float64]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def get_scales(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedInteractionGroup_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, row_atom_idxs_i: numpy.typing.NDArray[numpy.int32], cutoff: typing.SupportsFloat | typing.SupportsIndex, col_atom_idxs_i: numpy.typing.NDArray[numpy.int32] | None = ..., disable_hilbert_sort: bool = ..., nblist_padding: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, row_atom_idxs_i: list[numpy.typing.NDArray[numpy.int32]], cutoff: typing.SupportsFloat | typing.SupportsIndex, col_atom_idxs_i: list[numpy.typing.NDArray[numpy.int32]] | None = ..., disable_hilbert_sort: bool = ..., nblist_padding: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def get_col_idxs(self) -> list[int]: ...
    def get_compute_col_grads(self) -> bool: ...
    def get_nblist_padding(self) -> float: ...
    def get_row_idxs(self) -> list[int]: ...
    @overload
    def set_atom_idxs(self, row_atom_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], col_atom_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def set_atom_idxs(self, row_atom_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], col_atom_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]]) -> None: ...
    def set_compute_col_grads(self, arg0: bool) -> None: ...
    def set_nblist_padding(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedInteractionGroup_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, row_atom_idxs_i: numpy.typing.NDArray[numpy.int32], cutoff: typing.SupportsFloat | typing.SupportsIndex, col_atom_idxs_i: numpy.typing.NDArray[numpy.int32] | None = ..., disable_hilbert_sort: bool = ..., nblist_padding: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, row_atom_idxs_i: list[numpy.typing.NDArray[numpy.int32]], cutoff: typing.SupportsFloat | typing.SupportsIndex, col_atom_idxs_i: list[numpy.typing.NDArray[numpy.int32]] | None = ..., disable_hilbert_sort: bool = ..., nblist_padding: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def get_col_idxs(self) -> list[int]: ...
    def get_compute_col_grads(self) -> bool: ...
    def get_nblist_padding(self) -> float: ...
    def get_row_idxs(self) -> list[int]: ...
    @overload
    def set_atom_idxs(self, row_atom_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], col_atom_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def set_atom_idxs(self, row_atom_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], col_atom_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]]) -> None: ...
    def set_compute_col_grads(self, arg0: bool) -> None: ...
    def set_nblist_padding(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedMolEnergyPotential_f32:
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, target_mols: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def execute(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedMolEnergyPotential_f64:
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, target_mols: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def execute(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedPairListPrecomputed_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedPairListPrecomputed_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedPairList_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], scales_i: numpy.typing.NDArray[numpy.float32], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: list[numpy.typing.NDArray[numpy.int32]], scales_i: list[numpy.typing.NDArray[numpy.float32]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def get_scales(self) -> numpy.typing.NDArray[numpy.float32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class NonbondedPairList_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], scales_i: numpy.typing.NDArray[numpy.float64], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, pair_idxs_i: list[numpy.typing.NDArray[numpy.int32]], scales_i: list[numpy.typing.NDArray[numpy.float64]], cutoff: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def get_scales(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class PeriodicTorsion_f32(Potential_f32):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class PeriodicTorsion_f64(Potential_f64):
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.int32]) -> None: ...
    @overload
    def __init__(self, num_atoms: typing.SupportsInt | typing.SupportsIndex, torsion_idxs: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.int32]]) -> None: ...
    def get_idxs(self) -> numpy.typing.NDArray[numpy.int32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class PotentialExecutor_f32:
    def __init__(self, parallel: bool = ...) -> None: ...
    def execute(self, pots: collections.abc.Sequence[Potential_f32], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float32]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch(self, pots: collections.abc.Sequence[Potential_f32], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float32]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch_sparse(self, pots: collections.abc.Sequence[Potential_f32], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float32]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], coords_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], params_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class PotentialExecutor_f64:
    def __init__(self, parallel: bool = ...) -> None: ...
    def execute(self, pots: collections.abc.Sequence[Potential_f64], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch(self, pots: collections.abc.Sequence[Potential_f64], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch_sparse(self, pots: collections.abc.Sequence[Potential_f64], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], coords_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], params_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Potential_f32:
    def __init__(self, *args, **kwargs) -> None: ...
    def execute(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], compute_du_dx: bool, compute_du_dp: bool, compute_u: bool) -> tuple: ...
    def execute_batch_sparse(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], coords_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], params_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], compute_du_dx: bool, compute_du_dp: bool, compute_u: bool) -> tuple: ...
    def execute_dim(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float32]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_du_dx(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...
    @overload
    def num_systems(self) -> int: ...
    @overload
    def num_systems(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class Potential_f64:
    def __init__(self, *args, **kwargs) -> None: ...
    def execute(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_batch(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], compute_du_dx: bool, compute_du_dp: bool, compute_u: bool) -> tuple: ...
    def execute_batch_sparse(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], boxes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], coords_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], params_batch_idxs: typing.Annotated[numpy.typing.ArrayLike, numpy.uint32], compute_du_dx: bool, compute_du_dp: bool, compute_u: bool) -> tuple: ...
    def execute_dim(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64]], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], compute_du_dx: bool = ..., compute_du_dp: bool = ..., compute_u: bool = ...) -> tuple: ...
    def execute_du_dx(self, coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...
    @overload
    def num_systems(self) -> int: ...
    @overload
    def num_systems(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class SegmentedSumExp_f32:
    def __init__(self, max_vals_per_segment: typing.SupportsInt | typing.SupportsIndex, num_segments: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def logsumexp(self, values: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> list[float]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class SegmentedSumExp_f64:
    def __init__(self, max_vals_per_segment: typing.SupportsInt | typing.SupportsIndex, num_segments: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def logsumexp(self, values: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> list[float]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class SegmentedWeightedRandomSampler_f32:
    def __init__(self, max_vals_per_segment: typing.SupportsInt | typing.SupportsIndex, segments: typing.SupportsInt | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def sample(self, weights: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> list[int]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class SegmentedWeightedRandomSampler_f64:
    def __init__(self, max_vals_per_segment: typing.SupportsInt | typing.SupportsIndex, segments: typing.SupportsInt | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def sample(self, weights: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> list[int]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class SummedPotential_f32(Potential_f32):
    def __init__(self, potentials: collections.abc.Sequence[Potential_f32], params_sizes: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], parallel: bool = ...) -> None: ...
    def get_potentials(self) -> list[Potential_f32]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class SummedPotential_f64(Potential_f64):
    def __init__(self, potentials: collections.abc.Sequence[Potential_f64], params_sizes: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], parallel: bool = ...) -> None: ...
    def get_potentials(self) -> list[Potential_f64]: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class TIBDExchangeMove_f32(BDExchangeMove_f32):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, ligand_idxs: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], target_mols: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], temperature: typing.SupportsFloat | typing.SupportsIndex, cutoff: typing.SupportsFloat | typing.SupportsIndex, radius: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex, num_proposals_per_move: typing.SupportsInt | typing.SupportsIndex, interval: typing.SupportsInt | typing.SupportsIndex, batch_size: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class TIBDExchangeMove_f64(BDExchangeMove_f64):
    def __init__(self, N: typing.SupportsInt | typing.SupportsIndex, ligand_idxs: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], target_mols: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], temperature: typing.SupportsFloat | typing.SupportsIndex, cutoff: typing.SupportsFloat | typing.SupportsIndex, radius: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex, num_proposals_per_move: typing.SupportsInt | typing.SupportsIndex, interval: typing.SupportsInt | typing.SupportsIndex, batch_size: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class VelocityVerletIntegrator_f32(Integrator_f32):
    def __init__(self, dt: typing.SupportsFloat | typing.SupportsIndex, cbs: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

class VelocityVerletIntegrator_f64(Integrator_f64):
    def __init__(self, dt: typing.SupportsFloat | typing.SupportsIndex, cbs: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    def __release_buffer__(self, *args, **kwargs): ...

def atom_by_atom_energies_f32(target_atoms: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], nb_cutoff: typing.SupportsFloat | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.float32]: ...
def atom_by_atom_energies_f64(target_atoms: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], params: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], nb_cutoff: typing.SupportsFloat | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.float64]: ...
def cuda_device_reset() -> None: ...
def inner_and_outer_mols_f32(center_atoms: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], group_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], radius: typing.SupportsFloat | typing.SupportsIndex) -> tuple: ...
def inner_and_outer_mols_f64(center_atoms: typing.Annotated[numpy.typing.ArrayLike, numpy.int32], coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], group_idxs: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], radius: typing.SupportsFloat | typing.SupportsIndex) -> tuple: ...
def rmsd_align(x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...
def rotate_and_translate_mol_f32(coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], quaternion: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...
def rotate_and_translate_mol_f64(coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], quaternion: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...
def rotate_coords_f32(coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], quaternions: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> numpy.typing.NDArray[numpy.float32]: ...
def rotate_coords_f64(coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], quaternions: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]: ...
def translations_inside_and_outside_sphere_host_f32(num_translations: typing.SupportsInt | typing.SupportsIndex, box: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], center: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], radius: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.float32]: ...
def translations_inside_and_outside_sphere_host_f64(num_translations: typing.SupportsInt | typing.SupportsIndex, box: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], center: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], radius: typing.SupportsFloat | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.float64]: ...
